features:
  - 'account_number'
  - 'rent_mortgage_payment'
  - 'current_employer'
  - 'address'
  - 'hire_date'
  - 'job_title'
  - 'status'
  - 'email'
  - 'monthly_income'
  - 'ln_dti_ratio'
  - 'credit_score'
  - 'credit_score_date'
  - 'months_employed'
  - 'years_employed'
  - 'ln_late_1_29'
  - 'ln_late_30_59'
  - 'ln_late_60_89'
  - 'ln_late_90_119'
  - 'ln_late_120_149'
  - 'ln_late_150_179'
  - 'ln_late_180_plus'
  - 'neg_balance'
  - 'no_deposit'
  - 'late_payment'
  - 'total_months_employed'

dependent:
  - 'status'